version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: authProvider
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: db_security
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - .docker/mysql:/var/lib/mysql
    ports:
      - 3310:3306